---
title: "Sharing research artefacts"
bibliography: ../quarto_site/references.bib
---

<!-- TODO: Remove this warning once completed assessment -->
**Please note: This is a template page and has not yet been completed**

This page evaluates the extent to which the original study meets the recommendations for the sharing of code and associated materials. We compare against two standards:

* **Best practice audit** - requirements from the best practice audit by @monks_computer_2023. The items in this audit were based on @the_turing_way_community_turing_2022, @taylor_open_2017, and @the_open_modeling_foundation_omf_reusability_2024.
* **STARS** - recommendations from the recently published STARS framework by @monks_towards_2024.

## Best practice audit

Of the **11** items in this audit:

<!-- TODO: Add counts from evaluation -->
* **X** were met fully (✅)
* **X** was met partially (🟡)
* **X** was not met (❌)

<!-- TODO: Fill in the table. Options are ✅ Fully, 🟡 Partially, or ❌ Not met -->
| Item | Description | Met by study? | Evidence/location |
| - | - | :-: | - |
| Digital Object Identifier (DOI) | Does the model have a DOI and promise of persistence? Can it be cited? | <!----> | <!----> |
| Open Researcher and Contributor ID (ORCID) | Is the model linked to one or more of the authors via an ORCID? | <!----> | <!----> |
| License | Does the repository have a recognised open license to control the use of code, liabilty and credit? | <!----> | <!----> |
| Model overview | Is there an obvious file that provides an overview of the repository/model and it purpose (e.g. in README file)? | <!----> | <!----> |
| Link to published paper | Do models shared externally from journal articles contain a link to the published article? | <!----> | <!----> |
| Steps to run code | Does the readme file or similar describe the steps required to execute the simulation model? | <!----> | <!----> |
| Formal dependency management | Has a formal tool, e.g. renv, conda, or poetry been used to manage software dependencies for the simulation model? | <!----> | <!----> |
| Informal dependency management | Has an informal list or description of software, or OS dependencies been provided? | <!----> | <!----> |
| Code testing | Is there any evidence of tests that have been applied to the code to check that it functions correctly? | <!----> | <!----> |
| Local execution | Can the simulation model and associated files be downloaded and in theory executed on a local machine | <!----> | <!----> |
| Remote execution | Can the simulation model be executed online using free or commercial infrastructure? | <!----> | <!----> |
: {tbl-colwidths="[25, 25, 25, 25]"}

## STARS

Of the **8** essential STARS components:

<!-- TODO: Add counts from evaluation -->
* **X** were met fully (✅)
* **X** was met partially (🟡)
* **X** was not met (❌)

Of the **5** optional STARS components:

<!-- TODO: Add counts from evaluation -->
* **X** was met fully (✅)
* **X** were not met (❌)

<!-- TODO: Fill in the table. Options are ✅ Fully, 🟡 Partially, or ❌ Not met -->
| Component | Description | Met by study? | Evidence/location |
| - | - | :-: | - |
| **Essential components** |
| Open license | Free and open-source software (FOSS) license (e.g. MIT, GNU Public License (GPL)) | <!----> | <!----> |
| Dependency management | Specify software libraries, version numbers and sources (e.g. dependency management tools like pip virtual environment, conda environment, poetry) | <!----> | <!----> |
| FOSS model | Coded in FOSS language (e.g. R, Julia, Python) | <!----> | <!----> |
| Minimum documentation | Minimal instructions (e.g. in README) that overview (a) what model does, (b) how to install and run model to obtain results, and (c) how to vary parameters to run new experiements | | |
| ORCID | ORCID for each study author | <!----> | <!----> |
| Citation information | Instructions on how to cite the research artefact (e.g. CITATION.cff file) | <!----> | <!----> |
| Remote code repository | Code available in a remote code repository (e.g. GitHub, GitLab, BitBucket) | <!----> | <!----> |
| Open science archive | Code stored in an open science archive with FORCE11 compliant citation and guaranteed persistance of digital artefacts (e.g. Figshare, Zenodo, the Open Science Framework (OSF), and the Computational Modeling in the Social and Ecological Sciences Network (CoMSES Net)) | <!----> | <!----> |
| **Optional components** |
| Enhanced documentation | Open and high quality documentation on how the model is implemented and works  (e.g. via notebooks and markdown files, brought together using software like Quarto and Jupyter Book). Suggested content includes:<br>• Plain english summary of project and model<br>• Clarifying license<br>• Citation instructions<br>• Contribution instructions<br>• Model installation instructions<br>• Structured code walk through of model<br>• Documentation of modelling cycle using TRACE<br>• Annotated simulation reporting guidelines<br>• Clear description of model validation including its intended purpose | <!----> | <!----> |
| Documentation hosting | Host documentation (e.g. with GitHub pages, GitLab pages, BitBucket Cloud, Quarto Pub) | <!----> | <!----> |
| Online coding environment | Provide an online environment where users can run and change code (e.g. BinderHub, Google Colaboratory, Deepnote) | <!----> | <!----> |
| Model interface | Provide web application interface to the model so it is accessible to less technical simulation users | <!----> | <!----> |
| Web app hosting | Host web app online (e.g. Streamlit Community Cloud, ShinyApps hosting) | <!----> | <!----> |
: {tbl-colwidths="[20, 35, 20, 25]"}